language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
deploy:
  provider: npm
  email: joel@oblador.se
  api_key:
    secure: "T7XJiVK5NW+8D8/Fo4NMM2kaU54MRFWmRf2b3hVpUIN8padSslLSxTqphB0A4GbiqMRj3POQfrtizD3e5riGwC1niv3HMus8FP6DcsOoIYOFvg/CXnsLSvyOsNQSNSDCt/IJ1PsgpkC7GjUc8UVEaBgCWfR+8SkdDoyIoO8ntEq10zxNub16za7heLEi9Nm+Ve39VPLMj5lbKufjbCL/APIx0xjQT09pvr3vY4/9XMPkujiPHY4xmcb4kdr5p4TS+k2Ax/wjVfk4UGBlr0L/t9tpOUEO1gsrY54BR4MywfSe+0/etXVt5u0D1BnUp1I+LnhqdFjaTVeBKQWfO6tCy55hrI8pGMx4tFVISzqYIHSlrIE+zMaOjBzYU4VhM6uRaCPfQ2+3S252aMX9IkKw0p5mhb35vx7lMXkm1dRFUIXgJfXlJM+Wg0IuVd5SxpnBlp5C4KKDnuXkHsFsWd49H65smQhig6gIw9N1pID03puW/aaDToLpzrU/Q+U1wIg29aWTw5aVQYT31xtW4ofqYaNpTkHwgiC2W4bu8Yk8x3yvfbb67eJYQtBPjsb9aswv8UYc5uEejYGy1B7IRCWEU7f8By52nJB24XGFbij6d4SLpX+MMhumxVt7o3yJiDpzZB7nFC+c0AZuy3CF2lLg2jbxe4XJKJogB6py18V7bLY="
  on:
    tags: true
    repo: oblador/react-native-progress
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
